### ISSUE TITLE
Broken icon on Device Info Page

### ISSUE THREAD

**Issue by airgradienthq** [airgradienthq/python-airgradient#22]
![image](https://github.com/airgradienthq/python-airgradient/assets/68736665/7162a36e-431f-4b54-b743-d48793b28a18)

**Comment by joostlek** [comment]
Yes, that's handled by the [brands repository](https://github.com/home-assistant/brands). After the core integration is merged, the brands PR will also be looked at and merged. If that's done in about a day (due to cache) the icons and logos are visibile.

But before we can do that, we need to have the brands ready, can you open the PR or supply the brands so I can open that PR?

**Comment by joostlek** [comment]
Fixed!
